### ISSUE TITLE
Update ARS to message asynchronous query status

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Relay#210]
TRAPI/async endpoints send http code 200 to indicate initial receipt with the internal TRAPI message "running".  

ARS needs to handle this.

**Comment by sstemann** [comment]
ARAGORN reported this issue recently, Mark will look into it

**Comment by Genomewide** [comment]
I was just working on some queries to try and get data through the ARAX interface for PMI so that we could be as thorough as possible for the drug repurposing case work.  ARAX and ARAGORN were showing no results for gene-gene hits which was suspicious.  Pulling up the results later shows that it was not done but the interface showed zero results and then updated to some results when finished running.

**Comment by Genomewide** [comment]
More information on this. 
When submitting the TRAPI Response identifier, ARAX shows code 200 and status done when it is not done.  

If you try to return ARAX results then you get "Query commenced. Will send result to https://ars.transltr.io/ars/api/messages/0551022b-a3c2-4ac5-acf7-29cc29725f2a"

And message: "Returned response is not TRAPI: {'description': 'Query commenced. Will send result to https://ars.transltr.io/ars/api/messages/0551022b-a3c2-4ac5-acf7-29cc29725f2a'}"

Waiting longer for the query to complete returns the same code 200 and status done, now shows the results.  

This makes it very difficult to know when the query is run.  ARAGON may also be doing this, but it is running the query fast enough that the error does not always show up.

**Comment by MarkDWilliams** [comment]
This has been resolved
