### ISSUE TITLE
Incorrect 598 Status in CI

### ISSUE THREAD

**Issue by MarkDWilliams** [NCATSTranslator/Relay#373]
This bug seems to be happening in CI to sync tool endpoints.  Could be due to recent changes to timeouts or the receipt of synchronous results.

![Screen Shot 2023-03-13 at 4 22 32 PM](https://user-images.githubusercontent.com/12091335/225016458-3025d918-da87-49ed-9b71-075ae8d4a68c.png)

**Comment by ShervinAbd92** [comment]
Found out the issue was coming from the fact that some tools (molepro, genetics,improving, opendirect...) don't have 'attribute' or 'name' fields in their original knowledge_graphs and therefore the code errored out when trying to add additional attributes or change the name for nodes. Implemented checks in code to take care of this problem. PR #374
